# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GO_VERSION: 1.18
jobs:
  all-checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{env.GO_VERSION}}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run go generate
      run: go mod download
    - name: Run go generate
      run: go generate ./...
    - name: Run tests
      run: go test -count=1 -v ./...
    - name: Check code coverage
      run: |
       go test -coverprofile=coverage.tmp.out ./test
        cat coverage.tmp.out | grep -v _mock.go > coverage.out
        go tool cover -html=coverage.out -o coverage.html
    - name: Add coverage.out to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-out
        path: ./coverage.out
    - name: Add coverage.html to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-html
        path: ./coverage.html
